# Generated by Django 4.0.5 on 2022-11-06 20:37

import cuser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuser', '0003_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                (
                    'cuser_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL
                    )
                ),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                (
                    'gender',
                    models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, verbose_name='Пол')
                ),
                (
                    'liked_users',
                    models.ManyToManyField(blank=True, related_name='liked_users_set', to='my_tinder.customuser')
                ),
                (
                    'unliked_users',
                    models.ManyToManyField(blank=True, related_name='unliked_users_set', to='my_tinder.customuser')
                ),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
            bases=('cuser.cuser',),
            managers=[
                ('objects', cuser.models.CUserManager()),
            ],
        ),
    ]
