# Generated by Django 4.0.2 on 2022-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0002_likedusers_customuser_like_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='like',
            field=models.BooleanField(choices=[('Нравится', 'Нравится'), ('Не_нравится', 'Не нравится')], default=False),
        ),
    ]
