# Generated by Django 4.0.5 on 2022-11-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
