# Generated by Django 4.0.2 on 2022-05-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0004_alter_customuser_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='like',
            new_name='likes',
        ),
    ]
