# Generated by Django 4.0.2 on 2022-05-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0005_rename_like_customuser_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='likes',
        ),
    ]
