# Generated by Django 4.0.2 on 2022-05-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0006_remove_customuser_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Понравившейся участник')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='liked_users',
        ),
        migrations.DeleteModel(
            name='LikedUsers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_tinder.likeduser'),
        ),
    ]
