# Generated by Django 4.0.2 on 2022-06-07 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0007_likeduser_remove_customuser_liked_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.DeleteModel(
            name='LikedUser',
        ),
    ]
