# Generated by Django 4.0.5 on 2022-06-16 15:02

from django.db import migrations, models
import my_tinder.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0008_remove_customuser_liked_user_customuser_liked_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[(my_tinder.models.Gender['FEMALE'], 'M'), (my_tinder.models.Gender['MALE'], 'F')], max_length=1, verbose_name='Пол'),
        ),
    ]
