# Generated by Django 4.0.5 on 2022-06-16 15:02

from django.db import migrations, models
import my_tinder.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0009_alter_customuser_options_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[(my_tinder.models.Gender['FEMALE'], 'M'), (my_tinder.models.Gender['MALE'], 'F')], max_length=1, verbose_name='Gender'),
        ),
    ]
