# Generated by Django 4.0.5 on 2022-08-31 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0013_alter_customuser_options_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
