# Generated by Django 4.0.5 on 2022-09-14 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tinder', '0014_remove_customuser_liked_users_customuser_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unliked_users',
            field=models.ManyToManyField(blank=True, related_name='unliked_users_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Участник с такой электронной почтой уже существует.'}, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_users_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
